# Generated by Django 5.2.9 on 2025-12-24 17:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0029_stagedtransactionmodel_matched_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntity',
            fields=[
                ('entitymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_ledger.entitymodel')),
                ('accounting_method', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Accounting Entity',
                'verbose_name_plural': 'Accounting Entities',
            },
            bases=('django_ledger.entitymodel',),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('tax_deductible', models.BooleanField(default=True)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coa_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.accountmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
