# Generated by Django 5.2.9 on 2025-12-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentity',
            name='accounting_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('accrual', 'Accrual')], default='accrual', max_length=20),
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
