# Generated by Django 5.2.9 on 2025-12-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingapplication',
            options={'verbose_name': 'Onboarding Application', 'verbose_name_plural': 'Onboarding Applications'},
        ),
        migrations.AddField(
            model_name='onboardingapplication',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUBMITTED', 'Submitted'), ('PROMOTED', 'Promoted')], default='DRAFT', max_length=20),
        ),
    ]
