"""
Django settings for shogun project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


load_dotenv(BASE_DIR / "envs/.env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)(z@k_49_)0uybr0f4ykjq92+!^unaaeksk0x1z@l$thw^q_)l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

SHARED_APPS = [
    "django_tenants",  # mandatory
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tenants",  # your tenant app
    "identity",
    "onboarding",
    # API Infrastructure - SHARED
    "rest_framework",  # Core DRF framework
    "rest_framework_simplejwt",  # JWT authentication
    "djoser",  # Auth endpoints
    "corsheaders",  # CORS handling
    "drf_spectacular",  # API documentation
]

TENANT_APPS = [
    # your tenant-specific apps
    "django_ledger",  #
    "accounting",
]


INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Must be before CommonMiddleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "shogun.urls"
PUBLIC_SCHEMA_URLCONF = "shogun.urls_public"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django_ledger.context.django_ledger_context",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

TENANT_MODEL = "tenants.Client"  # app.Model

TENANT_DOMAIN_MODEL = "tenants.Domain"  # app.Model

# Custom user model
AUTH_USER_MODEL = "identity.User"

WSGI_APPLICATION = "shogun.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("SHOGUN_POSTGRES_DB", "shogun_db"),
        "USER": os.getenv("SHOGUN_POSTGRES_USER", "shogun_user"),
        "PASSWORD": os.getenv("SHOGUN_POSTGRES_PASSWORD", "shogun_password"),
        "HOST": os.getenv("SHOGUN_POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("SHOGUN_POSTGRES_PORT", "5435"),
    }
}


DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    # 'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication',
    # 'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    # 'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    # 'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    # 'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    # 'TOKEN_OBTAIN_SERIALIZER': 'accounts.serializers.TokenObtainPairSerializer',
    # 'TOKEN_REFRESH_SERIALIZER': 'accounts.serializers.TokenRefreshSerializer',
    # 'TOKEN_VERIFY_SERIALIZER': 'accounts.serializers.TokenVerifySerializer',
    "EXCEPTION_HANDLER": "accounts.utils.custom_exception_handler",
    "NON_FIELD_ERRORS_KEY": "non_field_errors",
}


REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "commons.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# REST_FRAMEWORK = {
#     # 'DEFAULT_AUTHENTICATION_CLASSES': (
#     #     'rest_framework.authentication.SessionAuthentication',  # Optional, for browsing API
#     #     'rest_framework.authentication.TokenAuthentication',  # If using token authentication
#     # ),
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "apps.accounts.authentication.CustomJWTAuthentication"
#     ],
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.IsAuthenticated",
#     ],
#     # YOUR SETTINGS
#     # "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
#     "EXCEPTION_HANDLER": "commons.exceptions.custom_exception_handler",
#     "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
# }

DRF_STANDARDIZED_ERRORS = {
    "EXCEPTION_FORMATTER_CLASS": "common.exceptions.APIExceptionFormatter"
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Shogun API",
    "DESCRIPTION": "API for Shogun project",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_URLCONF": "shogun.urls_public",
    "SCHEMA_PATH_PREFIX": "/api/schema",
    # OTHER SETTINGS
}
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3002",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:8000",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Allow all HTTP methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# Allow common headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Preflight cache duration
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours

# Disable automatic APPEND_SLASH to avoid redirects in API
APPEND_SLASH = False


LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
